### ISSUE TITLE
Site wide view restrictions block the OpauthController

### ISSUE THREAD

**Issue by stephenmcm** [BetterBrief/silverstripe-opauth#28]
If a Site has "Who can view pages on this site?" set to anything other than "Anyone" the OpauthController fails the `ContentController::init()` permission check on line 109.

A fix for this appears to be hard setting the access of the `OpauthController`'s `$dataRecord` like so:

``` php
    /**
     * Fake a Page_Controller by using that class as a failover
     */
    public function __construct($dataRecord = null) {
        if(class_exists('Page_Controller')) {
            $dataRecord = new Page_Controller($dataRecord);
            //Force the canView of page to avoid issue with site-wide access restrictions
            $dataRecord->dataRecord->CanViewType = 'Anyone';
        }
        parent::__construct($dataRecord);
    }
```

I'll keep testing but are there any security concerns stemming from this?

**Comment by willmorgan** [comment]
Ooh, nice catch. I'm not sure of the other options here, but maybe it's an idea to open this up to a properly permission based system where it can be disabled, if necessary.

**Comment by stephenmcm** [comment]
My other solution was to add a `OAPage_Controller` wrapper with the `canView()` method just set to return true. I guess adding an `OAPage_Controller` with an extension point on the `canView` method, might be suitable?

**Comment by willmorgan** [comment]
I think that's the most elegant way tbh. Mind submitting a PR? ;)

**Comment by stephenmcm** [comment]
Making sure, I haven't missed a semi-colon now. Should it default to allow access or to follow the site setting and require extension?

**Comment by willmorgan** [comment]
It should follow the site setting and require extension, but if `$this->extend(...` is null, it should return true.

**Comment by stephenmcm** [comment]
Okay so before I make a pull request, I've got 2 solutions:
``` php
class OAPage_Controller extends Page_Controller {
	
	public function canView($member = null) {
		$canView = parent::canView($member);
		$this->extend('alterCanView', $canView);
		
		return $canView;
	}
}
```
Or
``` php
class OAPage_Controller extends Page_Controller {
	
	public function canView($member = null) {
		if(OpauthController::config()->CanViewType) {
			$this->dataRecord->CanViewType = OpauthController::config()->CanViewType;
		}

		return parent::canView($member);
	}
}
```
The second is set via:
``` yml
OpauthController:
  CanViewType: 'Anyone'
```
The second set makes it easy to set up but looses some control, I guess a third option would be to mash the two together.

**Comment by willmorgan** [comment]
```php
class OpauthPageController extends Page_Controller {

    public function canView($member = null) {
        $canView = parent::canView($member);
        $this->extend('canView', $canView);

        return $canView;
    }
}
```

**Comment by dhensby** [comment]
I thought we were trying to decouple from the CMS...

**Comment by stephenmcm** [comment]
Given that we're still guarded by `class_exists('Page_Controller')` it's only coupled when the CMS is present. I haven't worked with SS framework without the CMS in place yet, but the can* checks are in `Controller::can()` so looking at the code alone it seems that without the CMS permission checks would again fail if the site is restricted by default?

**Comment by dhensby** [comment]
yes and no, the class that extends Page_Controller isn't wrapped in the `if` but nor should it be, because we should be defining our dependencies.

My point was more, this is just re-enforcing our coupling with the CMS rather than moving towards a separation.

Though, I think it's a bit academic at the moment as this module probably needs a re-write. Opauth has a new version (though it seems to have gone all quiet on it) and I think this module needs better defined remit (ie: just an oauth interface and then have the member jazz dealt with separately)

**Comment by Wernervanrun** [comment]
Why not extend Controller instead of ContentController, should fix the issue.

**Comment by dhensby** [comment]
**DISCLAIMER: This module depends on [Opauth](https://github.com/opauth/opauth/) which is no longer maintained - we don't recommend continuing to use this module as we aren't actively developing it any longer.**

---

Originally it did extend `Controller` but that had other issues that meant moving to `ContentController` was required
