### ISSUE TITLE
Custom log in form

### ISSUE THREAD

**Issue by mrvudo** [BetterBrief/silverstripe-opauth#30]
Is there a way to customise the layout of the form?
At the moment the module adds tabs to the log in page. I assume this might be an inbuilt SS thing.
Is there a way to customise this or even a short code to add the content in the "Social login" tab to the content area instead of the ugly tab.
![image](https://cloud.githubusercontent.com/assets/10969869/8398011/593cd7e4-1de0-11e5-9df9-09e6026b2cad.png)

**Comment by willmorgan** [comment]
Yes, [it's possible](http://willmorgan.co.uk/img/greggs/01-signin.jpg), but out of scope for this module as it's part of SilverStripe core and down to the developer on how to do this.

Off the top of my head, I think you might need to have a look at LoginForm.ss or similar.
