### ISSUE TITLE
[Recoverable Error] Argument 1 passed to DataExtension::validate() must be an instance of ValidationResult

### ISSUE THREAD

**Issue by hex0id** [BetterBrief/silverstripe-opauth#31]
opauth seems to be incompatible with clean install of SS 3.2, here's my composer file:
```
{
	"name": "silverstripe/installer",
	"description": "The Temp Project Requirements",
	"require": {
		"php": ">=5.3.2",
	  	"gdmedia/ss-auto-git-ignore": "dev-master",
		"silverstripe/cms": "3.2.1",
		"silverstripe/framework": "3.2.1",
        "betterbrief/silverstripe-opauth": "dev-master",
		"opauth/facebook": "^0.2.1"
	},
	"config": {
		"process-timeout": 600	
	},
  "scripts": {
    "post-update-cmd": "GDM\\SSAutoGitIgnore\\UpdateScript::Go"
  },
	"minimum-stability": "dev"
}
```

Here's what I get when I am trying to authenticate with FB:
```
[Recoverable Error] Argument 1 passed to DataExtension::validate() must be an instance of ValidationResult, none given
GET /opauth/finished/
Line 42 in /Users/alex/Sites/temp.dev/public/framework/model/DataExtension.php
Source
33 		throw new Exception('unload_extra_statics gone');
34 	}
35 
36 	/**
37 	 * Hook for extension-specific validation.
38 	 *
39 	 * @param $validationResult Local validation result
40 	 * @throws ValidationException
41 	 */
42 	public function validate(ValidationResult $validationResult) {
43 	}
44 
45 	/**
46 	 * Edit the given query object to support queries for this extension
47 	 *
48 	 * @param SQLQuery $query Query to augment.
Trace
DataExtension->validate() 
call_user_func_array(Array,Array) 
Object.php:707
Object->__call(validate,Array) 
OpauthController.php:124
Member->validate() 
OpauthController.php:124
OpauthController->finished(SS_HTTPRequest) 
RequestHandler.php:288
RequestHandler->handleAction(SS_HTTPRequest,finished) 
Controller.php:200
Controller->handleAction(SS_HTTPRequest,finished) 
RequestHandler.php:200
RequestHandler->handleRequest(SS_HTTPRequest,DataModel) 
Controller.php:157
Controller->handleRequest(SS_HTTPRequest,DataModel) 
ContentController.php:198
ContentController->handleRequest(SS_HTTPRequest,DataModel) 
Director.php:385
Director::handleRequest(SS_HTTPRequest,Session,DataModel) 
Director.php:149
Director::direct(/opauth/finished/,DataModel) 
main.php:184
```

Problem goes away when I change requirements to 3.1.

**Comment by dhensby** [comment]
Thanks for reporting this; I'll take a look and see what I can do to get it working

**Comment by dhensby** [comment]
This is very strange - it seems to be calling `validate` on the extension instead of on the `Member` object itself... The `DataExtension` should only have the method called by the `->extend()` call on a `Member`... this *could* be a core issue - I don't see how it's anything inherently wrong with this moduel

**Comment by tractorcow** [comment]
OpauthController should not be calling `$member->validate`, which is a protected method.

**Comment by dhensby** [comment]
@tractorcow is right, this method is protected which is causing the problem.

It was not protected in 3.1

see issue on core: https://github.com/silverstripe/silverstripe-framework/issues/4798

**Comment by tractorcow** [comment]
Yeah but DataObject::validate is protected in both 3.1 and 3.2.

It looks like Member::validate was the exception. I guess that means we need to make it public in 3.2.2?

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/4799

**Comment by kinglozzer** [comment]
@dhensby If you need an immediate workaround, you could call `->doValidate()` instead (though that method only exists since 3.2) :)

**Comment by dhensby** [comment]
@hex0id if you run 3.2.x-dev as your framework dep, this will now work.

**Comment by dhensby** [comment]
@hex0id we've done some work to bring the module up to speed - it's lacked some love recently.

I've tagged a v2 alpha release, would you mind letting us know if anything has broken in our upgrade (https://github.com/BetterBrief/silverstripe-opauth/releases/tag/v2.0.0-alpha.1) thanks!

**Comment by hex0id** [comment]
I sure will ;) it's in one of my active projects, thank you all guys.

On Fri, Dec 4, 2015 at 12:10 PM, Daniel Hensby <notifications@github.com>
wrote:

> @hex0id <https://github.com/hex0id> we've done some work to bring the
> module up to speed - it's lacked some love recently.
>
> I've tagged a v2 alpha release, would you mind letting us know if anything
> has broken in our upgrade (
> https://github.com/BetterBrief/silverstripe-opauth/releases/tag/v2.0.0-alpha.1)
> thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BetterBrief/silverstripe-opauth/issues/31#issuecomment-162024034>
> .
>



-- 
Regards, Alex.
