### ISSUE TITLE
Cannot install v1.1.2 with composer

### ISSUE THREAD

**Issue by wernerkrauss** [BetterBrief/silverstripe-opauth#36]
Problem 1
    - betterbrief/silverstripe-opauth v1.1.2 requires opauth/opauth ~0.4.5 -> no matching package found.
    - betterbrief/silverstripe-opauth 1.1.x-dev requires opauth/opauth ~0.4.5 -> no matching package found.
    - Installation request for betterbrief/silverstripe-opauth ^1.1.2 -> satisfiable by betterbrief/silverstripe-opauth[1.1.x-dev, v1.1.2].

Somehow your composer.json is a bit bogus? Do we need a 1.0 version?

**Comment by wernerkrauss** [comment]
I currently fixed it by this settings in my composer.json:

```
"betterbrief/silverstripe-opauth": "1.1.x",
"opauth/opauth": "1.0.0-alpha.1 as 0.4.5"
```

**Comment by dhensby** [comment]
Opauth 1.0 is not compatble with v1.1 of this module.

You need to add this to your composer:

```
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/dhensby/opauth"
        }
    ]
```

Unfortunately opauth is abandoned and so this module probably needs to be too :(

**Comment by wernerkrauss** [comment]
yup, noticed that V1 is not working, so i installed 0.4.4 now.
