### ISSUE TITLE
Users still authenticated when linkOnMatch is off

### ISSUE THREAD

**Issue by Wernervanrun** [BetterBrief/silverstripe-opauth#40]
linkOnMatch is a serious security issue, what would happen if i set my LinkedIn or Facebook primary email to match any admin email address.
Even with this setting disabled users are still authenticated!!!
If an attacker would know any admin email they could use LinkedIn or Facebook primary email address to login as admin.

**Comment by dhensby** [comment]
**DISCLAIMER: This module depends on [Opauth](https://github.com/opauth/opauth/) which is no longer maintained - we don't recommend continuing to use this module as we aren't actively developing it any longer.**

---

Have you confirmed this issue in the wild? When this was originally built we checked how these services allowed emails to be set and you always had to confirm ownership of them to use them on those sites.

If the setting is being ignored, then that needs patching. We'd be happy to accept PRs

**Comment by dhensby** [comment]
Just to follow up:

![](https://dl.dropboxusercontent.com/u/3429338/Clippings/2016-06/2016-06-01_10-42-30-vL0JcpK3am.png)

**Comment by willmorgan** [comment]
Hmm, this is an interesting find. I guess this goes down to the root of how ID providers are supposed to function, and how much they can be trusted.

Identity providers by definition should be trusted to prove the identity of the person logging in. This also means that we'd expect an ID provider to do their "due diligence" to confirm the identity of the person beforehand... so sure, if an ID provider doesn't confirm the email address of a person before including that email address in their ID response, then we have a problem.

Some instant workarounds to protect against this sort of thing come to mind:

1. Using an email address label for admin emails. (like `john+admin24309734@doe.com`)
2. Using default admin to log in only.
3. Being careful about what ID providers you trust.

If this isn't the case, then patches would be welcome. I am pretty snowed under with my own commitments at the moment and we're close to abandoning the module, but thanks for filing this.

**Comment by dhensby** [comment]
As far as I'm concerned if you're using a service to authenticate your users and they don't verify your users' data, then don't use that service as you can't actually use them to authenticate anything.

However, it does sound like link on match is broken so I've renamed this issue.

**Comment by Wernervanrun** [comment]
Sorry, it is just something i noticed when reviewing the code for use in one of my projects.
There are too many providers for me to check them all and keep checking them, maybe i should have said potential serious security issue issue.
Maybe the readme should mention this potential security issue this way people are aware.

**Comment by willmorgan** [comment]
Sure... or perhaps you could have PM'd one of the maintainers...

**Comment by Wernervanrun** [comment]
Still authenticate user when linkOnMatch is false is a security issue when users have multiple social media accounts wich are verified some of wich are maintained  multiple admins.

Admin makes cms account user info@mycompany.com
Admin makes linkedin account info@mycompany.com
Admin makes Facebook account info@mycompany.com

User B is going to manage Facebook
Admin is probably not aware that User B can get into his Cms account...

It was stupid to post security issue directly sorry may bad.....
Made multiple long days when i was confronted whith this issue.
I felt the need to let it be knows but my head was still mostly with my own project.

Will not happen again.

**Comment by dhensby** [comment]
No worries; it's not like we've documented how to report security issues.

We probably should document the linkOnMatch function a bit better and highlight any theoretical issues, but ID providers need to be whitelisted (I think?!) to be used on a site, so any that don't provide proper verification of ID should not be enabled regardless of this.

I'd accept a PR with better docs or just removing this "feature" entirely.

**Comment by Wernervanrun** [comment]
It's tricky you could fix the authentication issue and disable by default with comment.
Than add yaml;
OpauthIdentity
    linkOnMatch: false
    misMatchGroups: 
        - Admin
        - Author

And check;
// existing user found
`if($linkOnMatch && !$member->inGroups($misMatchGroups))`

**Comment by dhensby** [comment]
Sounds like a great solution. Feel free to PR :)

**Comment by Wernervanrun** [comment]
I will try to find some time.
Not sure when though.

**Comment by dhensby** [comment]
No problem :)
