### ISSUE TITLE
Issue with TwitterStrategy

### ISSUE THREAD

**Issue by sunnysideupdevs** [BetterBrief/silverstripe-opauth#41]
Hi there
I have tried using the Twitter Strategy with this module and there seems to be a bug with
parsing the data coming back from Twitter ... any ideas on updates or fixes for this?

Cheers
Jack

![twitterstratgey](https://cloud.githubusercontent.com/assets/20271919/16548141/8c39e114-41d9-11e6-813a-79d154cac9a6.png)

**Comment by dhensby** [comment]
**DISCLAIMER: This module depends on [Opauth](https://github.com/opauth/opauth/) which is no longer maintained - we don't recommend continuing to use this module as we aren't actively developing it any longer.**

---

Looks like user error on your part. The member mapper you need to define needs to have a source path that is a "callable" it seems...

**Comment by dhensby** [comment]
It may be worth looking into https://github.com/bigfork/SilverStripe-OAuth / https://github.com/bigfork/SilverStripe-OAuth-Login
