### ISSUE TITLE
Google strategy "hd" parameter

### ISSUE THREAD

**Issue by tungdt-90** [BetterBrief/silverstripe-opauth#43]
Currently, i'm on a project which required to filter the google email. That means it should only accept email with @yourcompany.com. These email are being integrated with google. 

I read the Open ID document, find out that i need to put "hd" parameter in to strategy config and modify the code.

But i'm not sure can i modify this module, or i must modify opauth module ?

**Comment by dhensby** [comment]
**DISCLAIMER: This module depends on [Opauth](https://github.com/opauth/opauth/) which is no longer maintained - we don't recommend continuing to use this module as we aren't actively developing it any longer.**

---

I don't think this is something that we can modify. Because it's specific to google you probably need to produce or edit the google provider. There might be a google apps provider for opauth, not sure.

**Comment by tungdt-90** [comment]
I see, thank you.
I'll try to find another way for this problem of mine.

**Comment by willmorgan** [comment]
@tungdt-90 It sounds like you can just modify the Google strategy.

**Comment by tungdt-90** [comment]
@willmorgan I tried already. It took me to the login page, asking me to put an email like "example@myproject.com". But after that, it still cannot register the user, guess because the token return cannot compare email with "hd" parameter.

Anyway, I removed this module from my project already, and I will try with new Google Sign In. Maybe i will be able to turn it into a new Google login module.

Thank you.

**Comment by willmorgan** [comment]
@tungdt-90 You can configure the mapping. If the email comes back in the `hd` parameter, simply update the mapping config for your Google strategy name. Docs here: https://github.com/BetterBrief/silverstripe-opauth#how-do-i-configure-the-module-and-its-strategies

``` yml
OpauthIdentity:
  member_mapper:
    Google:
      FirstName: 'info.first_name'
      Surname: 'info.last_name'
      Email: 'info.hd'
      Locale: ['OpauthResponseHelper', 'get_google_locale']
```

You can use dot access notation to traverse the JSON that Google returns.

Good luck either way...

**Comment by tungdt-90** [comment]
Thanks for your help @willmorgan ,

I didn't realized that in oauth2callback function, i can just split and compare user's email with the email i put in "hd" parameter, process if it true and throw out error if it's not. So now it worked for me.

**Comment by willmorgan** [comment]
@tungdt-90 Cool! Are you using the module after all?

**Comment by tungdt-90** [comment]
@willmorgan Yeah !

I was in a hurry, no time for a new module, so i went back to this module, then i did what you said. I modified GoogleStrategy.php, catch the return `$userinfo['email']` and compare it with `$this->strategy['email']`.

The result was quite good actually, it only accepts emails with @myproject.com
